# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "booms", :force => true do |t|
    t.column "link",       :text,     :default => "", :null => false
    t.column "title",      :string,   :default => "", :null => false
    t.column "created_at", :datetime,                 :null => false
    t.column "user_id",    :integer,                  :null => false
    t.column "kind",       :string,   :default => "", :null => false
    t.column "popularity", :integer,  :default => 0,  :null => false
  end

  add_index "booms", ["user_id"], :name => "index_booms_on_user_id"
  add_index "booms", ["created_at"], :name => "index_booms_on_created_at"
  add_index "booms", ["popularity"], :name => "index_booms_on_popularity"

  create_table "points", :force => true do |t|
    t.column "boom_id", :integer
    t.column "user_id", :integer
  end

  add_index "points", ["boom_id", "user_id"], :name => "index_points_on_boom_id_and_user_id", :unique => true
  add_index "points", ["user_id"], :name => "index_points_on_user_id"
  add_index "points", ["boom_id"], :name => "index_points_on_boom_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "boom_id", :integer
    t.column "tag_id",  :integer
  end

  add_index "taggings", ["boom_id", "tag_id"], :name => "index_taggings_on_boom_id_and_tag_id", :unique => true
  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["boom_id"], :name => "index_taggings_on_boom_id"

  create_table "tags", :force => true do |t|
    t.column "name",       :string
    t.column "slug",       :string
    t.column "popularity", :integer
  end

  add_index "tags", ["popularity"], :name => "index_tags_on_popularity"

  create_table "users", :force => true do |t|
    t.column "nick",     :string,  :default => "", :null => false
    t.column "email",    :string,  :default => "", :null => false
    t.column "password", :string,  :default => "", :null => false
    t.column "admin",    :boolean
  end

  add_index "users", ["email"], :name => "index_users_on_email"

end
